20_08_20_after/project_revise/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tot.urls'))
]

20_08_20_after/project_revise/tot/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name='tot'

urlpatterns = [
    path('', views.index, name='index'),
    path('graph/', views.graph, name='graph'),
    path('search/', views.search, name='search'),
    path('youtube/', views.youtube, name='youtube'),
    path('anal/', views.anal, name='anal'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

20_08_20_after/project_revise/tot/models.py
from django.db import models
from jsonfield import JSONField

# Create your models here.
class Keyword(models.Model):
    word = models.CharField(max_length=45)
    date = models.DateField()
    high_word_frequency = JSONField(default={}, dump_kwargs={'ensure_ascii': False})
    created = models.DateTimeField(auto_now_add=True)

20_08_20_after/project_revise/tot/views.py
from django.shortcuts import render, redirect
from pytrends.request import TrendReq
from datetime import datetime, time, timedelta
from .harvesta import harvesta
from .preproca import preproca
import json
import requests
import sys
import subprocess
import os
import DateTime
from math import log10
from konlpy.tag import Mecab
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import defaultdict
import shutil
import nltk
import re
from konlpy.corpus import kolaw
from konlpy.utils import pprint
from konlpy.tag import Mecab
#from nltk.corpus import treebank
from .models import Keyword
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
import csv
import os.path
from dotenv import load_dotenv
load_dotenv()
# Create your views here.
def index(request):

    return render(request, 'tot/index.html')

def graph(request):
    print(os.getcwd())
    words = request.GET.get('q')
    if not words:
        return redirect('tot:index')
    date = request.GET.get('y')
    a = ','
    pytrends = TrendReq(timeout=(5,35))
    #pytrends = TrendReq(hl='ko', tz=540, timeout=(5, 35))
    print(pytrends)
    try:
        if a not in words:
            if request.GET.get('y')=='year':
                date = 'today 12-m'
            elif request.GET.get('y')=='month':
                date = 'today 1-m'
            else:
                date = 'now 7-d'
            word1 = words
            list1 = [word1]
            pytrends.build_payload(list1, cat=0, timeframe= f'{date}', geo='', gprop='')
            #pytrends.build_payload(list1, cat=0, timeframe= f'{date}', geo='', gprop='youtube')
            value = pytrends.interest_over_time()
            #print(value)
            del value['isPartial']
            value = value.reset_index()
            value2 = value.to_json(force_ascii=False, orient='split', date_format='iso', date_unit='s')
            value_dict = json.loads(value2)
            value_word1 = []
            for a in value_dict['data']:
                k = {}
                h = datetime.strptime(a[0],'%Y-%m-%dT%H:%M:%SZ')
                h2 = h.strftime('%Y-%m-%d %H:%M:%S')
                k['label'] = h2
                k['y'] = a[1]
                #k['link'] = '/anal'
                value_word1.append(k)
            dict1 = pytrends.related_queries()
            dict2 = dict1[f'{word1}']
            newdict1 = {}
            if len(dict2['top']['value']) > 10:
                newdict1 = dict2['top'][0:10]
                newdict1 = newdict1.to_dict()
            else:
                newdict1 = dict2['top']
                newdict1 = newdict1.to_dict()
            context = {'vw1':value_word1, 'word1':word1, 'newdict1': newdict1, 'date':date}
            return render(request, 'tot/graph.html', context)
        elif a in words:
            pass
            words = words.split(',')
            word1 = words[0]
            word2 = words[1]
            if request.GET.get('y')== 'year':
                date = 'today 12-m'
            elif request.GET.get('y') == 'month':
                date = 'today 1-m'
            else:
                date = 'now 7-d'
            list1 = [word1, word2]
            pytrends.build_payload(list1, cat=0, timeframe= f'{date}', geo='US', gprop='')
            value = pytrends.interest_over_time()
            del value['isPartial']
            value = value.reset_index()
            value2 = value.to_json(force_ascii=False, orient='split', date_format='iso', date_unit='s')
            value_dict = json.loads(value2)
            value_word1 = []
            value_word2 = []
            for a in value_dict['data']:
                k = {}
                z = {}
                h = datetime.strptime(a[0],'%Y-%m-%dT%H:%M:%SZ')
                h2 = h.strftime('%Y-%m-%d %H:%M:%S')
                k['label'] = h2
                k['y'] = a[1]
                #k['link'] = '/anal'
                value_word1.append(k)
                z['label'] = h2
                z['y'] = a[2]
                #z['link'] = '/anal'
                value_word2.append(z)
            dict1 = pytrends.related_queries()
            dict2 = dict1[f'{word1}']
            dict3 = dict1[f'{word2}']
            newdict1 = {}
            newdict2 = {}
            if len(dict2['top']['value']) > 10:
                newdict1 = dict2['top'][0:10]
                newdict1 = newdict1.to_dict()
            else:
                newdict1 = dict2['top']
                newdict1 = newdict1.to_dict()
            if len(dict3['top']['value']) > 10:
                newdict2 = dict3['top'][0:10]
                newdict2 = newdict2.to_dict()
            else:
                newdict2 = dict3['top']
                newdict2 = newdict2.to_dict()


            context = {'vw1':value_word1, 'vw2':value_word2, 'word1':word1, 'word2':word2, 'newdict2':newdict2, 'newdict1':newdict1, 'date':date}
            return render(request, 'tot/graph.html', context)
    except:
        return redirect('tot:index')


def search(request):
    if request.GET.get('word2'):
        word1 = request.GET.get('word1')
        word2 = request.GET.get('word2')
        word3 = request.GET.get('cd')
        date = request.GET.get('date')
        list1 = [word1, word2]
        pytrends = TrendReq(hl='ko', tz=540, timeout=(7, 35))
        pytrends.build_payload(list1, cat=0, timeframe= f'{date}', geo='', gprop='youtube')
        dict1 = pytrends.related_queries()
        dict2= dict1[f'{word3}']
        bubble = []
        if len(dict2['top']['value'])>10:
            for n in range(0,10):
                bbw1 = {}
                bbw1['text'] = dict2['top']['query'][n]
                bbw1['count'] = dict2['top']['value'][n]
                bubble.append(bbw1)
        else:
            for n in range(0, len(dict2['top']['value'])):
                bbw1 = {}
                bbw1['text'] = dict2['top']['query'][n]
                bbw1['count'] = dict2['top']['value'][n]
                bubble.append(bbw1)
        context = {'bubble':bubble, 'date':date}

        return render(request, 'tot/search.html', context)
    else:
        word1 = request.GET.get('word1')
        word3 = request.GET.get('cd')
        date = request.GET.get('date')
        list1 = [word1]
        pytrends = TrendReq()
        pytrends.build_payload(list1, cat=0, timeframe= f'{date}', geo='', gprop='youtube')
        dict1 = pytrends.related_queries()
        dict2= dict1[f'{word3}']
        bubble = []

        if len(dict2['top']['value'])>10:
            for n in range(0,10):
                bbw1 = {}
                bbw1['text'] = dict2['top']['query'][n]
                bbw1['count'] = dict2['top']['value'][n]
                bubble.append(bbw1)
        else:
            for n in range(0, len(dict2['top']['value'])):
                bbw1 = {}
                bbw1['text'] = dict2['top']['query'][n]
                bbw1['count'] = dict2['top']['value'][n]
                bubble.append(bbw1)
        context = {'bubble':bubble, 'date':date}
        return render(request, 'tot/search.html', context)

def youtube(request):
    date = request.GET.get('date')
    text = request.GET.get('text')
    return render(request, 'tot/youtube.html')

def anal(request):
    date = request.GET.get('date')
    keyword = request.GET.get('keyword')
    datebf7 = datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
    date1 = datebf7.strftime('%Y-%m-%d %H:%M:%S')
    date1 = date1[0:10]
    date1 = str(date1)
    print(date1,"힘내라 친구여")
    keyword3 = Keyword.objects.filter(word=keyword, date=date1).values().exists()
    print(keyword3, "키워드3")
    if keyword3:
        keyword2 = Keyword.objects.filter(word=keyword, date=date1).values()
        keyword_word = keyword2[0]['word']
        keyword_date = keyword2[0]['date']
        keyword_hwf = keyword2[0]['high_word_frequency']
        print(keyword_hwf)
        print(type(keyword_hwf))
        keyword_hwf_1 = json.loads(keyword_hwf, encoding='utf-8')
        print(keyword_hwf_1)
        print(type(keyword_hwf_1))
        keyword_hwf_2 = keyword_hwf_1
        print(keyword_hwf_2, "키워트hwf2")
        hwf_values = [i for i in keyword_hwf_2.values()]
        hwf_keys = [i for i in keyword_hwf_2.keys()]
        #print(hwf_values[0])
        #print(hwf_values)
        #print()
        #print(keyword_hwf_2)
        #print(keyword_hwf_2[f'{hwf_keys[2]}'])
        hwf_list = []
        for key in keyword_hwf_2.keys():
            st = {}
            st['text'] = key
            st['frequency'] = keyword_hwf_2[key]
            hwf_list.append(st)
        #print(hwf_list)
        #print(hwf_list)
        #print(hwf_keys[0])
        a = hwf_keys[0]
        b = hwf_keys[1]
        c = hwf_keys[7]
        print(hwf_list,"테스트")
        created = keyword2[0]['created'].strftime('%Y%m%d%H%M%S')
        urls, titles = read_csv(created)
        title_urls = zip(urls, titles)
        context = {'keyword_word':keyword_word, 'title_urls':title_urls, 'hwf_list':hwf_list, 'a':a, 'b':b, 'c':c}
        return render(request, 'tot/anal.html', context)
    else:
        #date = request.GET.get('date')
        #keyword = request.GET.get('keyword')
        #datebf7 = datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
        datebf8 = datebf7 + timedelta(days=-7)
        datebf8 = datebf8.strftime('%Y%m%d %H:%M:%S')
        date = datebf7.strftime('%Y%m%d %H:%M:%S')
        #date1 = datebf7.strftime('%Y-%m-%d %H:%M:%S')
        #date1 = date1[0:10]
        date = date[0:8]
        datebf7 = datebf8[0:8]
        startpath ='./'
        keyword_source_dic = {'ENTERPRISE':[f'{keyword}']}
        print(keyword_source_dic,"나는 어제가 좋아")
        outPath = harvesta.harvest(startpath, datebf7, date, keyword_source_dic)
        print(outPath,"나는 오늘이 좋아")
        preproca.preproc(outPath)
        current_time = datetime.today().strftime("%Y%m%d%H%M%S")
        print(current_time)
        #current_ymd = current_time[2:8]

20_08_20_after/project_revise/tot/templates/tot/anal.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
   {% autoescape off %}
    <style>
      .abc {
        caption-side: top;
      }
      body {
        background-color:#222222;
      }
      table {
        width: 100%;
        height: 100px;
        table-layout:fixed;
        text-align: center;
      }

      table, tr, th,
      td {
        padding: 20px;
        color: white;
        border: 1px solid #080808;
        border-collapse: collapse
        font-size:18px;
        font-family:Arial;
        background:lineaer-gradient(top, #3c3c3c 0%, #222222 100%);
        background:-webkit-linear-gradient(top, #3c3c3c 0%, #222222 100%);

      }
      td:hover{
        background:blue;
      }
    </style>
</head>
 {% endautoescape %}
<body>
  <nav class="navbar navbar-light bg-primary">
    <a class="navbar-brand text-white" href="{% url 'tot:index' %}">trend of tracer</a>
  </nav>
  <div class="row">
    <div class="col-md-6">
  <table style="margin:auto;">
    <tr>
      <th>기사태그</th>
    </tr>
    {% for url,title in title_urls %}
    <tr>
      <td><a href="{{ url }}" style="color:white;">{{title}}</a><br></td>
    </tr>
    {% endfor %}
  </table>
  </div>
   {% if hwf_list %}
  <div class="col-md-6">
  <table>
    <tr>
      <th>기사에서 많이나온 단어</th>
      <th>빈도수</th>
    </tr>
  {% for i in hwf_list %}
  <tr>
     <td>{{i.text}}</td>
     <td>{{i.frequency}}</td>
  </tr>
  {% endfor %}
</table>
</div>
{% elif result2 %}
<div class="col-md-6">
<table>
  <tr>
    <th>기사에서 많이나온 단어</th>
    <th>빈도수</th>
  </tr>
{% for i in result2 %}
<tr>
   <td>{{i.0}}</td>
   <td>{{i.1}}</td>
</tr>
{% endfor %}
</table>
</div>
{% endif %}
</div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>
</html>

20_08_20_after/project_revise/tot/templates/tot/graph.html
{% load static %}
{% load value_idx %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Graph</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <style>
    .abc { caption-side: top;
    }
    
  /*
  Side Navigation Menu V2, RWD
  ===================
  License:
  https://goo.gl/EaUPrt
  ===================
  Author: @PableraShow

  */

  
  @import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,700);
  @charset "UTF-8";
  body {
  font-family: 'Open Sans', sans-serif;
  font-weight: 300;
  line-height: 1.42em;
  color: white;
  background-color:#1F2739;
  }

  h1 {
  font-size:3em;
  font-weight: 300;
  line-height:1em;
  text-align: center;
  color: #4DC3FA;
  }

  h2 {
  font-size:1em;
  font-weight: 300;
  text-align: center;
  display: block;
  line-height:1em;
  padding-bottom: 2em;
  color: #FB667A;
  }

  h2 a {
  font-weight: 700;
  text-transform: uppercase;
  color: #FB667A;
  text-decoration: none;
  }

  .blue { color: #185875; }
  .yellow { color: #FFF842; }

  .container th h1 {
  font-weight: bold;
  font-size: 1em;
  text-align: left;
  color: #185875;
  }

  .container td {
  font-weight: normal;
  font-size: 1em;
  -webkit-box-shadow: 0 2px 2px -2px #0E1119;
  -moz-box-shadow: 0 2px 2px -2px #0E1119;
  box-shadow: 0 2px 2px -2px #0E1119;
  }

  .container {
  text-align: left;
  overflow: hidden;
  width: 80%;
  margin: 0 auto;
  display: table;
  padding: 0 0 8em 0;
  }

  .container td, .container th {
  padding-bottom: 2%;
  padding-top: 2%;
  padding-left:2%;
  }

  /* Background-color of the odd rows */
  .container tr:nth-child(odd) {
  background-color: #323C50;
  }

  /* Background-color of the even rows */
  .container tr:nth-child(even) {
  background-color: #2C3446;
  }

  .container th {
  background-color: #1F2739;
  }

  .container td:first-child { color: #FB667A; }

  .container tr:hover {
  background-color: #464A52;
  -webkit-box-shadow: 0 6px 6px -6px #0E1119;
  -moz-box-shadow: 0 6px 6px -6px #0E1119;
  box-shadow: 0 6px 6px -6px #0E1119;
  }

  .container td:hover {
  background-color: #FFF842;
  color: #403E10;
  font-weight: bold;

  box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px
  6px;
  transform: translate3d(6px, -6px, 0);

  transition-delay: 0s;
  transition-duration: 0.4s;
  transition-property: all;
  transition-timing-function: line;
  }

  @media (max-width: 800px) {
  .container td:nth-child(4),
  .container th:nth-child(4) { display: none; }
  }

  </style>
    {% autoescape off %}
  <script>
    window.onload = function () {

      var chart = new CanvasJS.Chart("chartContainer", {
        theme: "light2",
        animationEnabled: true,
        backgroundColor: "#1F2739",
        fontColor: "white",
        
        title: {
          fontColor: "white",
          {% if word2 %}
          text: "{{word1}}과 {{word2}}의 트렌드 " 
          {% else %}
          text: "{{word1}}의 트렌드" 
          {% endif %}
        },

        axisX: {
          labelFontStyle: "normal",
          labelAngle: null,

        },
        axisY: {
          includeZero: false,
          title: "트렌드 검색 수치",
          maximum: 102,
          gridColor: "black",
          fontColor: "white",

        },
        toolTip: {
          shared: "true"
        },
        legend: {
          cursor: "pointer",
          itemclick: toggleDataSeries,
          fontColor: "white",
        },
        data: [{
            type: "spline",
            click: onClick,
            showInLegend: true, // 그래프를 보여줌
            yValueFormatString: "",
            name: "{{word1}}",
            fontColor: "white",
            dataPoints: {{ vw1 }}

          },
          {% if word2 %} 
          {
            type: "spline",
            showInLegend: true, // 그래프를 보여줌
            click: onClick,
            yValueFormatString: "",
            name: "{{word2}}",
            dataPoints: {{ vw2 }}
          } 
          {% endif %}
        ]

      });

      chart.render();
      // 적용된 것을 랜더 시킴
      function onClick(e) {

        //window.open(e.dataPoint.link, '_blank');
        //console.log(e.dataPoint.label);
        //console.log(e.dataSeries.name);
        //window.open('/anal?date='+e.dataPoint.label+'&'+'keyword='+e.dataSeries.name, '_blank')
        window.location.href = '/anal?date=' + e.dataPoint.label + '&' + 'keyword=' + e.dataSeries.name;

      }


      function toggleDataSeries(e) {
        if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
          e.dataSeries.visible = false;
          // 눌르면 어둡게 하면 .. 차트 사라짐
        } else {
          e.dataSeries.visible = true;
          // 다시 밣히면 차트 보임
        }
        chart.render();
      }

    }
  </script>
  
  {% endautoescape %}
  </head>
<body>
  <!--<div id = 'loading'>
    <img src='/static/img/3.jpg'>
  </div>-->
  <!--<script>
    $(function () {
      $('#loading').css('visibility', 'hidden');
    });
  </script>-->

  <nav class="navbar navbar-light bg-primary">
    <a class="navbar-brand text-white" href="{% url 'tot:index' %}">trend of tracer</a>
  </nav>
  <div id="chartContainer" style="height: 400px; width: 100%;  margin-top:20px; margin-left:20px; margin-bottom:20px" ></div>
   <hr>
   {% if word2 %}
   <div class="row">
     <div class="col-md-6">
       <table class="container">
         <caption class='abc'><a
             href="{% url 'tot:search' %}?word1={{ word1 }}&word2={{ word2 }}&cd={{word1}}&date={{date}}"
             onclick="this.parentNode.submit()">{{word1}}의 유튜브 연관검색어</a></caption> <br />
         <thead>
           <tr>
             <th>
               <h1>구글 연관 검색어</h1>
             </th>
             <th><h1>검색어 지수</h1></th>
           </tr>
         </thead>
         <tbody>
           {% for i,v in newdict1.query.items %}
           <!--{#{ newdict1.lue|value_by_key:forloop.counter0 }}-->
           <tr>
             <td>{{v}}</td>
             <td>{{newdict1.value|value_by_key:forloop.counter0}}</td>
           </tr>
           {% endfor %}
         </tbody>
       </table>
     </div>
     <div class="col-md-6">
       <table class="container">
         <form action="{% url 'tot:search' %}?word1={{ word1 }}&word2={{ word2 }}" method="GET">
           <caption class='abc'><a
               href="{% url 'tot:search' %}?word1={{ word1 }}&word2={{ word2 }}&cd={{word2}}&date={{date}}"
               onclick="this.parentNode.submit()">{{word2}}의 유튜브 연관검색어</a></caption> <br />
         </form>
         <thead>
           <tr>
             <th>
               <h1>구글 연관 검색어</h1>
             </th>
             <th><h1>검색어 지수</h1></th>
           </tr>
         </thead>
         <tbody>
           {% for i,v in newdict2.query.items %}
           <!--{#{ newdict1.value|value_by_key:forloop.counter0 }}-->
           <tr>
             <td>{{v}}</td>
             <td>{{newdict2.value|value_by_key:forloop.counter0}}</td>
           </tr>
           {% endfor %}
         </tbody>
       </table>
     </div>
   </div>
   {% else %}
   <table class='container'>
     <form action="{% url 'tot:search' %}?word1={{ word1 }}" method="GET">
       <caption class='abc'><a href="{% url 'tot:search' %}?word1={{ word1 }}&cd={{word1}}&date={{date}}">{{word1}}의
           연관검색어</a></caption> <br />
     </form>
     <thead>
       <tr>
         <th>
           <h1>구글 연관 검색어</h1>
         </th>
         <th>
           <h1>검색어 지수</h1>
         </th>
       </tr>
     </thead>
     <tbody>
       {% for i,v in newdict1.query.items %}
       <!--{#{ newdict1.value|value_by_key:forloop.counter0 }}-->
       <tr>
         <td>{{v}}</td>
         <td>{{newdict1.value|value_by_key:forloop.counter0}}</td>
       </tr>
       {% endfor %}
     </tbody>
   </table>
   {% endif %}

   <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
   <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
   <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
     integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
   </script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
     integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
   </script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
     integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
   </script>
   </body>

   </html>

20_08_20_after/project_revise/tot/templates/tot/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="img1">

  <div class="img1-search">
    <form action="{% url 'tot:graph'%}" method="GET">
      <fieldset>
        <legend>tot 키워드 검색!</legend>
        <div class="inner-form">
          <div class="input-field">
            <input class="form-control" id="choices-text-preset-values" type="text" name='q' placeholder="키워드 검색은 2개까지" />
            <button class="btn-search" type="button" onclick="this.parentNode.parentNode.parentNode.parentNode.submit()">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path
                  d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z">
                </path>
              </svg>
            </button>
          </div>
        </div>
        <div class="suggestion-wrap">
          <input type="radio" name="y" value="year"><span>최근 1년</span>
          <input type="radio" name="y" value="month"><span>최근 1달</span>
          <input type="radio" name="y" value="7day"><span>최근 7일</span>
        </div>
      </fieldset>
    </form>
  </div>

<!--<script src="{#% static 'js/choices.js' %}"></script>-->
<script src="/static/js/choices.js"></script>
<script>
  var textPresetVal = new Choices('#choices-text-preset-values',
    {
      removeItemButton: true,
    });

</script>

{% endblock %}
</html>