20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/urls.py
from django.urls import path
from . import views

app_name= "question"
urlpatterns = [
        path('', views.index, name='index'),
        path('new/', views.new, name="new"),
        path('<int:que_id>', views.detail, name="detail"),
        path('<int:que_id>/edit/', views.edit, name="edit"),
        path('<int:que_id>/delete/', views.delete, name="delete"),
        path('<int:que_id>/survey/', views.survey, name="survey"),
        path('<int:c_id>/survey_edit/', views.survey_edit, name="survey_edit"),
        path('<int:c_id>/survey_delete/', views.survey_del, name="sur_del"),
        path('<int:c_id>/vote/', views.vote, name="vote"),
        ]

20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f'{self.id} > {self.question}'
class Choice(models.Model):
    survey = models.CharField(max_length=100)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.id}'

20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice
# Create your views here.
def index(request):
    questions = Question.objects.all()

    context = {
            'questions': questions
    }
    return render(request, 'question/index.html', context)
def new(request):
    if request.method == "POST":
        question = Question(question=request.POST.get('question'))
        question.save()
        return redirect('question:index')
    else:
        return render(request, 'question/new.html')
def detail(request, que_id):
    question = Question.objects.get(id=que_id)
    surveys = question.choice_set.all()
    context = {

            'question': question,
            'surveys': surveys


            }
    return render(request, 'question/detail.html', context)

def edit(request, que_id):
    que = Question.objects.get(id=que_id)
    if request.method == "POST":
        text = request.POST.get('question')
        que.question = text
        que.save()
        return redirect('question:detail', que.id)
    else:
        context = {
                "question":que
        }
        return render(request, 'question/edit.html', context)
def delete(request, que_id):
    que = Question.objects.get(id=que_id)
    if request.method == "POST":
        que.delete()
    return redirect('question:index')
def survey(request, que_id):
    question = Question.objects.get(id=que_id)
    if request.method == "POST":
        text = request.POST.get('survey')
        s = Choice()
        s.survey = text
        s.question = question
        s.save()
    return redirect('question:detail', question.id)
def survey_edit(request, c_id):
    survey = Choice.objects.get(id=c_id)

    if request.method == "POST":
        text = request.POST.get('survey')
        if text != survey.survey:
            survey.votes = 0
        survey.survey = text
        survey.save()

        return redirect('question:detail', survey.question_id)
    else:
        context = {
                "survey": survey
                }
        return render(request, 'question/sur_edit.html', context)
def survey_del(request, c_id):
    survey = Choice.objects.get(id=c_id)
    if request.method == "POST":
        survey.delete()

    return redirect('question:detail', survey.question_id)
def vote(request, c_id):
    survey = Choice.objects.get(id=c_id)
    if request.method == "POST":
        survey.votes += 1
        survey.save()
        return redirect('question:detail', survey.question_id)

20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/templates/question/detail.html
{% extends 'base.html' %}
{% block body %}
<h2>{{ question.question }}</h2>
<a href="{% url 'question:edit' question.id %}">수정하기</a>

<form action = '{% url "question:delete" question.id %}' method='POST'>
	{% csrf_token %}
	<input type='submit' value="삭제하기">
</form>
<hr><br>
<ol>
	{% for sur in surveys %}
	<li>
		<form action="{% url 'question:vote' sur.id %}" method="POST">
			{% csrf_token %}
		{{ sur.survey }}[{{ sur.votes }}]
		<a href="#" onclick="this.parentNode.submit()">투표하기</a>
		<a href="{% url 'question:survey_edit' sur.id %}">수정하기</a>
		</form>
	</li>
	{% empty %}
	<h2>등록해 주세여.</h2>
	{% endfor %}
</ol>

<hr><br>
<form action='{% url "question:survey" question.id %}' method="post">
	{% csrf_token %}
	질문답변 <input type="text" name="survey">
	<input type="submit">
</form>
{% endblock %}

20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/templates/question/edit.html
{% extends 'base.html' %}
{% block body %}
<form action='' method='POST'>
	{% csrf_token %}
	<input type="text" name="question" value="{{ question.question }}">
	<input type="submit">
</form>
{% endblock %}

20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/templates/question/index.html
{% extends 'base.html' %}
{% block body %}
<h1>who is future question god?</h1>
<h3>funny question list</h3>
<ul>
	{% for que in questions %}
	<li><a href="{% url 'question:detail' que.id %}">{{que.question}}</a></li>
	{% empty %}
	<h2> 질문 등록이 필요하지 않을까?</h2>
	{% endfor %}

</ul>
{% endblock %}

20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/templates/question/new.html
{% extends 'base.html' %}
{% block body %}
    <form action='' method='POST'>
        {% csrf_token %}
        질문등록: <input type="text" name="question"><br>
        <input type='submit' value='등록하기'>
    </form>
{% endblock %}

20_08_20_before/Project/Final_Project/Basic/Basic-Practice6/question/templates/question/sur_edit.html
{% extends 'base.html' %}
{% block body %}
<form action="" method='post'>
	{% csrf_token %}
	<input type="text" name="survey" value="{{ survey.survey }}">
	<input type='submit' value="수정하기">
</form>

<form action='{% url "question:sur_del" survey.id %}' method='POST'>
	{% csrf_token %}
	<input type='submit' value="삭제하기">
</form>
{% endblock %} 